import React, { ReactElement } from "react";
import { Header } from "./Header";
import { Footer } from "./Footer";
import Head from "next/head";

export default function Layout({ Children }) {
  return (
    <>
      <Head>
        <meta charset="UTF-8" />
        <title>Amaten|ホーム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Ten.ico" />
      </Head>
      <div>
        <header>
          <Header />
        </header>
        <main>{Children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
}
