import Head from "next/head";
import styles from "../styles/amatenPay.module.css";

import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { HeaderBottom } from "../components/HeaderBottom";

export default function amatenPay() {
  return (
    <div className={styles.container}>
      <Head>
        <meta charSet="UTF-8" />
        <title>Amaten|Pay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Ten.ico" />
      </Head>
      <Header />
      <HeaderBottom />

      <div className={styles.content}>
        <div className={styles.title}>amaten Pay</div>
      </div>

      <Footer />
    </div>
  );
}
