import Head from "next/head";
import styles from "../styles/history.module.css";
import Link from "next/link";
import { useEffect, useState, useCallback } from "react";
import { db } from "../components/firebase";
import { getAuth, onAuthStateChanged } from "firebase/auth";
import { collection, doc, getDoc, setDoc, getDocs } from "firebase/firestore";

import { Footer } from "../components/Footer";
import { HeaderBottom } from "../components/HeaderBottom";
import { Header } from "../components/Header";

export default function history() {
  const [name, setName] = useState("");
  const [history, setHistory] = useState([]);

  //マウント時に誰がログインしているか確認する。firebaseAuth
  useEffect(() => {
    //asyncのために関数を定義
    const StateProfile = async () => {
      //これで誰がログインしているか分かる
      const auth = getAuth();
      onAuthStateChanged(auth, async (user) => {
        //ユーザがいれば
        if (!user) {
          window.location.href = "/login";
          return;
        }
        const uid = user.uid;
        //ユーザー名取得
        const docRef = doc(db, "users", uid);
        const docSnap = await getDoc(docRef);
        console.log(docSnap);
        setName(docSnap.data().name);
        //購入履歴を取得

        const checkoutsSnap = await getDocs(
          collection(db, "users", uid, "checkouts")
        );
        //取得した購入履歴をforEachで取り出していく
        const checkouts = [];
        checkoutsSnap.forEach((his) => {
          checkouts.push(his.data());
        });
        console.log(checkouts);
        setHistory(checkouts);
      });
    };
    StateProfile();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <meta charSet="UTF-8" />
        <title>Amaten|購入履歴</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Ten.ico" />
      </Head>
      <Header />
      <HeaderBottom />
      <div className={styles.content}>購入履歴</div>
      <div>{name}さん</div>

      <div>
        {history
          .sort((a, b) => b.time - a.time)
          .map((his, i) => (
            <div key={i}>
              <div className={styles.historys}>
                <Link href={his.item_url} target="_blank">
                  <div className={styles.cap}>
                    <img src={his.img} alt="" />
                    {his.description}
                  </div>
                </Link>
                <div></div>
                <div>{his.total}円</div>
                <div>
                  購入時刻 :　
                  {new Intl.DateTimeFormat("ja-JP", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                    hour: "2-digit",
                    minute: "2-digit",
                    second: "2-digit",
                  }).format(new Date(his.time))}
                </div>
                {/* Format timestamp as desired */}
              </div>
            </div>
          ))}
      </div>

      <Footer />
    </div>
  );
}
